// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumidIOTChange();
void onRainIOTChange();
void onTempIOTChange();
void onWindDirIOTChange();
void onWindSpeedIOTChange();
void onLEDChange();

float humidIOT;
float rainIOT;
float tempIOT;
float windDirIOT;
float windSpeedIOT;
bool lED;

void initProperties(){

  ArduinoCloud.addProperty(humidIOT, READWRITE, ON_CHANGE, onHumidIOTChange);
  ArduinoCloud.addProperty(rainIOT, READWRITE, ON_CHANGE, onRainIOTChange);
  ArduinoCloud.addProperty(tempIOT, READWRITE, ON_CHANGE, onTempIOTChange);
  ArduinoCloud.addProperty(windDirIOT, READWRITE, ON_CHANGE, onWindDirIOTChange);
  ArduinoCloud.addProperty(windSpeedIOT, READWRITE, ON_CHANGE, onWindSpeedIOTChange);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
